### ISSUE TITLE
Enable RSTcheckBear on all coala repos with .rst files

### ISSUE THREAD

**Issue by jayvdb** [coala/coala#3044]
c.f. coala/coala-bears/issues/902

Most of bugs found by RSTcheckBear in documentation have already been raised as separate bugs.

e.g. https://github.com/coala/documentation/issues?utf8=%E2%9C%93&q=RSTcheck

Since I raised those bugs, more bugs have been created in the `documentation` repo.

And other repos also have one error.

```
coala$ find . -name '*.rst' | xargs rstcheck 
./README.rst:193: (WARNING/2) Explicit markup ends without a blank line; unexpected unindent.

coala-bears$ find . -name '*.rst' | xargs rstcheck 
./RELEASE_NOTES.rst:222: (WARNING/2) Duplicate explicit target name: "here".

coala-quickstart$ find . -name '*.rst' | xargs rstcheck
README.rst:4: (WARNING/2) Title underline too short.
```

Thore errors from RSTcheckBear should be raised as one "newcomer" bug per error , with a link back here.

Then, there are two generators that need to be improved - needs analysis to see if they are difficulty newcomer or low:

```
./aspect-docs/Metadata/CommitMessage/README.rst:10: (INFO/1) Duplicate implicit target name: "commitmessage".
./aspect-docs/Metadata/CommitMessage/Body/Length/README.rst:10: (INFO/1) Duplicate implicit target name: "length".
./aspect-docs/Metadata/CommitMessage/Body/README.rst:10: (INFO/1) Duplicate implicit target name: "body".
./aspect-docs/Metadata/CommitMessage/Body/Existence/README.rst:10: (INFO/1) Duplicate implicit target name: "existence".
./aspect-docs/Metadata/CommitMessage/Emptiness/README.rst:10: (INFO/1) Duplicate implicit target name: "emptiness".
./aspect-docs/Metadata/CommitMessage/Shortlog/Length/README.rst:10: (INFO/1) Duplicate implicit target name: "length".
./aspect-docs/Metadata/CommitMessage/Shortlog/README.rst:10: (INFO/1) Duplicate implicit target name: "shortlog".
./aspect-docs/Metadata/CommitMessage/Shortlog/ColonExistence/README.rst:10: (INFO/1) Duplicate implicit target name: "colonexistence".
./aspect-docs/Metadata/CommitMessage/Shortlog/TrailingPeriod/README.rst:10: (INFO/1) Duplicate implicit target name: "trailingperiod".
./aspect-docs/Metadata/CommitMessage/Shortlog/FirstCharacter/README.rst:10: (INFO/1) Duplicate implicit target name: "firstcharacter".
./aspect-docs/Metadata/CommitMessage/Shortlog/Tense/README.rst:10: (INFO/1) Duplicate implicit target name: "tense".
./aspect-docs/Metadata/README.rst:10: (INFO/1) Duplicate implicit target name: "metadata".
./aspect-docs/README.rst:2: (WARNING/2) Duplicate explicit target name: "length".
./bear-docs/docs/HappinessLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/TSLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/GoLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/DockerfileLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/PEP8NotebookBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/JSComplexityBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/BootLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/XMLBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/DartLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/LanguageToolBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/VintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/CSecurityBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/BanditBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/MypyBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/CoffeeLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/InferBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/ClangComplexityBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/FormatRBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/RubySmellBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/GoVetBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/SQLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/KeywordBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/GoTypeBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/VHDLLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/ESLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/ClangCloneDetectionBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/SpellCheckBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/JavaPMDBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/PerlCriticBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/CPPLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/PyUnusedCodeBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/LineLengthBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/WriteGoodLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/CasingBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/MarkdownBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/CPPCleanBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/GNUIndentBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/MatlabIndentationBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/reSTLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/GoImportsBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/SCSSLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/VultureBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/YAMLLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/PuppetLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/ScalaLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/RubySyntaxBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/CSVLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/JSHintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/CPDBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/CPPCheckBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/JSONFormatBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/PyImportSortBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/PEP8Bear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/HaskellLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/IndentationBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/coalaBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/ShellCheckBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/QuotesBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/PyCommentedCodeBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/CheckstyleBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/GoReturnsBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/PycodestyleBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/CSSAutoPrefixBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/GoErrCheckBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/RuboCopBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/FilenameBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/ClangASTPrintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/LatexLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/InvalidLinkBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/CSSLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/SpaceConsistencyBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/AnnotationBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/ClangFunctionDifferenceBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/GitCommitBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/LuaLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/TailorBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/RadonBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/HTMLLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/CSharpLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/RLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/JuliaLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/RAMLLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/PHPLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/PHPCodeSnifferBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/GofmtBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/ClangBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/ProseLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/PyDocStyleBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/CMakeLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/VerilogLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/LineCountBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/Jinja2Bear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/YapfBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/AlexBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/docs/PyLintBear.rst:2: (WARNING/2) Title underline too short.
./bear-docs/README.rst:9: (WARNING/2) Title underline too short.
```

**Comment by jayvdb** [comment]
Once https://github.com/coala/coala-bears/issues/1028 is built, we can implement that also, which prevents problems like https://github.com/coala/coala/issues/3078

**Comment by jayvdb** [comment]
The above generated rst errors are fixed, however there are still more.  Please run `rstcheck` on the generated output.

```
aspect-docs$ find . -name '*.rst' | xargs rstcheck 
./Metadata/CommitMessage/Body/Length/README.rst:49: (WARNING/2) Title underline too short.
./Metadata/CommitMessage/Body/Existence/README.rst:33: (WARNING/2) Title underline too short.
./Metadata/CommitMessage/Emptiness/README.rst:34: (WARNING/2) Title underline too short.
./Metadata/CommitMessage/Shortlog/Length/README.rst:48: (WARNING/2) Title underline too short.
./Metadata/CommitMessage/Shortlog/ColonExistence/README.rst:51: (WARNING/2) Title underline too short.
./Metadata/CommitMessage/Shortlog/TrailingPeriod/README.rst:50: (WARNING/2) Title underline too short.
./Metadata/CommitMessage/Shortlog/FirstCharacter/README.rst:54: (WARNING/2) Title underline too short.
./Metadata/CommitMessage/Shortlog/Tense/README.rst:17: (ERROR/3) Malformed table.
./README.rst:2: (WARNING/2) Duplicate explicit target name: "length".
./Redundancy/Clone/README.rst:64: (WARNING/2) Title underline too short.
./Redundancy/UnreachableCode/README.rst:19: (WARNING/2) Bullet list ends without a blank line; unexpected unindent.
./Redundancy/UnreachableCode/UnusedFunction/README.rst:37: (WARNING/2) Title underline too short.
./Redundancy/UnreachableCode/UnreachableStatement/README.rst:35: (WARNING/2) Title underline too short.
./Redundancy/README.rst:20: (WARNING/2) Bullet list ends without a blank line; unexpected unindent.
./Redundancy/UnusedImport/README.rst:39: (WARNING/2) Title underline too short.
./Redundancy/UnusedVariable/UnusedParameter/README.rst:34: (WARNING/2) Title underline too short.
./Redundancy/UnusedVariable/README.rst:19: (WARNING/2) Bullet list ends without a blank line; unexpected unindent.
./Redundancy/UnusedVariable/UnusedLocalVariable/README.rst:35: (WARNING/2) Title underline too short.
./Redundancy/UnusedVariable/UnusedGlobalVariable/README.rst:34: (WARNING/2) Title underline too short.
```

```
bear-docs$ find . -name '*.rst' | xargs rstcheck 
./docs/HappinessLintBear.rst:2: (INFO/1) Duplicate implicit target name: "happinesslintbear".
./docs/TSLintBear.rst:2: (INFO/1) Duplicate implicit target name: "tslintbear".
./docs/GoLintBear.rst:2: (INFO/1) Duplicate implicit target name: "golintbear".
./docs/DockerfileLintBear.rst:2: (INFO/1) Duplicate implicit target name: "dockerfilelintbear".
./docs/PEP8NotebookBear.rst:2: (INFO/1) Duplicate implicit target name: "pep8notebookbear".
...
./README.rst:43: (INFO/1) Duplicate explicit target name: "cpdbear".
```

That last one appears to not be a generated file.

**Comment by jayvdb** [comment]
`rst-lint` warnings looks to be a superset of `rstcheck` warnings, *and* maybe `rstcheck` only shows one error per line while `rst-lint` shows them all.

Here are some of the extra messages shows by `rst-lint`:

`Cannot analyze code. No Pygments lexer found for "English".`

`WARNING ./bear-docs/docs/InvalidLinkBear.rst:27 Inline substitution_reference start-string without end-string.`

```
INFO ./coala-bears/docs/index.rst:17 No directive entry for "toctree" in module "docutils.parsers.rst.languages.en".
Trying "toctree" as canonical directive name.
ERROR ./coala-bears/docs/index.rst:17 Unknown directive type "toctree".
...
INFO ./documentation/Developers/Development_Setup.rst:22 No role entry for "ref" in module "docutils.parsers.rst.languages.en".
Trying "ref" as canonical role name.
ERROR ./documentation/Developers/Development_Setup.rst:22 Unknown interpreted text role "ref".
INFO ./documentation/Developers/Development_Setup.rst:1 Hyperlink target "dev-notes" is not referenced.
```

**Comment by Mixih** [comment]
most should have issues assigned now. I grouped all underline issues together. Still getting the hang of rst, so there may be a few false alarms

**Comment by Mixih** [comment]
Issues I spawned:
Documentation:
    https://github.com/coala/documentation/issues/331
    https://github.com/coala/documentation/issues/330
    https://github.com/coala/documentation/issues/329
bear-docs:
    https://github.com/coala/bear-docs/issues/23
aspect-docs:
    https://github.com/coala/aspect-docs/issues/3
    https://github.com/coala/aspect-docs/issues/4

Will add more to this list as I find them

**Comment by jayvdb** [comment]
I've created a beginner GCI task for newcomer documentation tasks, so we need to get the rst bears enabled quickly. Harass anyone not finishing an assigned task.

**Comment by Mixih** [comment]
@jayvdb No has bit on any of my issues yet... Should I start fixing them as they're critical now?

**Comment by jayvdb** [comment]
We still have time; the GCI task hasnt been published yet, and the first people doing this GCI task can be given these bugs to fix, so please dont do them, otherwise we loose our pool of newcomer documentation bugs.
IMO we stop allocating other newcomer issues until these ones are allocated and resolved.

> aspect-docs:
> coala/aspect-docs#3
> coala/aspect-docs#4

are these generated files?  If so, they are probably 'low', and maybe we should do it?

**Comment by Mixih** [comment]
yeah, they're probably generated....

**Comment by Mixih** [comment]
Repos that needs checks:

- [ ] Documentation
- [ ] Coala-bears
- [ ] Coala

**Comment by jayvdb** [comment]
Status update

- [x] Documentation
- [x] Coala-bears
- [ ] Coala : https://github.com/coala/coala/issues/4209

**Comment by jayvdb** [comment]
We have an issue for the remaining repo, and https://github.com/coala/meta/issues/117 will take the concept further.  Closing this to clear the plate.
