### ISSUE TITLE
[bug] Disable cache option not working

### ISSUE THREAD

**Issue by adhikasp** [coala/coala#3081]
Hello,

I found a possible bug of cannot disable caching mode.

Step to reproduce

1. Install and configure coala as usual.
2. Run `coala`, found some lint error, ignore all bugs
3. Run coala again, found no bugs 
4. Run `coala --disable-caching` got following error:

```
[ERROR][22:16:26] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][22:16:26] Exception was:
Traceback (most recent call last):

  File "/home/dhika/.local/lib/python3.5/site-packages/coalib/coala_main.py", line 80, in run_coala
    settings_hash = get_settings_hash(sections, targets)

  File "/home/dhika/.local/lib/python3.5/site-packages/coalib/misc/CachingUtilities.py", line 149, in get_settings_hash
    section_copy.delete_setting(setting)

  File "/home/dhika/.local/lib/python3.5/site-packages/coalib/settings/Section.py", line 255, in delete_setting
    del self.contents[key]

KeyError: 'disable_caching'
```

I'm also trying to build coala in Travis with disable cache option and got error too.
<https://travis-ci.org/adhikasp/discourse_docker/builds/177567740>

Update: the `--flush-caching` is working, mistake on me.

**Comment by Makman2** [comment]
Seems the issue is resolved. @adhikasp please close the issue next time or at least write a separate comment, otherwise we won't get notified and we may miss your updates :+1:

**Comment by adhikasp** [comment]
@Makman2 
No the issue is not resolved
- `coala --flush-caching` is actually working, but
- `coala --disable-caching` is throwing above error

Sorry for the misunderstanding

**Comment by Makman2** [comment]
Can't reproduce, works as intended:
```
mak@hp-elitebook-2540p:~$ coala --disable-caching
[WARNING][16:21:02] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag.
[WARNING][16:21:02] coala will not run any analysis. Did you forget to give the `--files` argument?
[WARNING][16:21:02] coala will not run any analysis. Did you forget to give the `--bears` argument?
mak@hp-elitebook-2540p:~$ coala --version
0.9.0.dev20161121122219
```
What version of coala do you use?

**Comment by Makman2** [comment]
never mind, confirmed 👍 

Happens after running coala again when the cache has already been built.
CC @adtac

**Comment by adtac** [comment]
yeah, this is a known issue (was brought up a few days ago)

I'll fix it soon :+1: (exams currently)

**Comment by RohanVB** [comment]
```
$ coala --disable-caching
[ERROR][17:35:12] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[INFO][17:35:12] Exception was:
Traceback (most recent call last):

  File "/Users/name/Virtualenv/virt1/lib/python3.5/site-packages/coalib/coala_main.py", line 84, in run_coala
    settings_hash = get_settings_hash(sections, targets)

  File "/Users/name/Virtualenv/virt1/lib/python3.5/site-packages/coalib/misc/CachingUtilities.py", line 149, in get_settings_hash
    section_copy.delete_setting(setting)

  File "/Users/name/Virtualenv/virt1/lib/python3.5/site-packages/coalib/settings/Section.py", line 255, in delete_setting
    del self.contents[key]

KeyError: 'disable_caching'

```

Issue may need to be reopened (may be related to https://github.com/coala/coala/issues/3639)

**Comment by Makman2** [comment]
@RohanVB on the most recent dev version? That's bad...

**Comment by RohanVB** [comment]
Yep looks like it, with `--pre` install.
@Makman2

**Comment by Makman2** [comment]
Just tried to execute coala on this repo, several times with and without `--disable-caching`, no errors on my isde. my coala version:
`0.10.0.dev20170127183105`

@RohanVB just seeing your version was most recent stable, `0.9.1`. Not sure we fixed that bug there already...

**Comment by RohanVB** [comment]
@Makman2 wasn't 0.9.1 released <1.5 months ago? I guess the issue was resolved ~2 months ago. 
Anyways, if the patch isn't in the stable version I guess we can close it. :)

**Comment by Makman2** [comment]
did you try with `0.10.dev`?

**Comment by jayvdb** [comment]
0.9.1 only includes some important patches created after 0.9. Maybe we missed this one.

**Comment by Makman2** [comment]
looks like, @jayvdb do you think we should backport right before the 0.10 release?
