### ISSUE TITLE
Inline ConsoleInteraction.nothing_done()

### ISSUE THREAD

**Issue by Makman2** [coala/coala#4523]
It's only used once, has a bad name and then we also don't need a specific test for it.

**Comment by aasiya13** [comment]
I am new to this project. how can i find the location of issue ??

**Comment by aasiya13** [comment]
i found the location where it has been mentioned. so do i need to remove the test case or what i can do to fix this.?

**Comment by SanketDG** [comment]
@aasiya13 Since `nothing_done()` has no advantages in being a function, we remove it and instead just use it inline where it is called, so basically copy the contents of the function to where its called and remove the original declaration

**Comment by chitranshi21** [comment]
please review the pull request for this issue .

https://github.com/coala/coala/pull/4558

**Comment by chitranshi21** [comment]
Hi, 

Can you assign the issue to me. I have submitted a patch already.

**Comment by Makman2** [comment]
Please ask and get assigned before you start working on an issue to avoid duplicated work. It seems that @aasiya13 had no time recently to start anyway, but please settle that before doing an issue 👍

**Comment by aasiya13** [comment]
it's okay. i had tough time last days. i'm really sorry for the inconvenience..

**Comment by Makman2** [comment]
@aasiya13 sure don't worry :D no inconvenience was caused by you ;)

**Comment by chitranshi21** [comment]
Hey @Makman2 Can you assign this issue to me now..?

**Comment by Makman2** [comment]
You haven't accepted the invitation from us yet, we can't assign you before :+1:

**Comment by chitranshi21** [comment]
done ..!! please assign me now .

**Comment by SanketDG** [comment]
@chitranshi21 you are assigned.

On a side note, you can also assign it yourself, https://api.coala.io/en/latest/Developers/Newcomers_Guide.html#step-2-picking-up-an-issue

**Comment by roshnet** [comment]
Hi. I see that this issue still persists. I would like to be assigned to it.
